"""
Django settings for newsibleasia project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/ 
"""
import os
from pathlib import Path

#for recon
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0*1-!85r4l-7h5ts!ri+cii%wm@s2wk7o#+w%7t!!a8x2$om1+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['newsibleasia.com','www.newsibleasia.com']
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.40']


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'easy_thumbnails',
    'image_cropping',
    'ckeditor',
    'ckeditor_uploader',
    'service',
    'post_management',
    'Ad_management',
    'Seo_management',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'journalist',
    'django_countries',
    'cities_light',
    'setting',
    'django_user_agents',
    'portal',
    'rest_framework',
    #'django_crontab',
    #'embed_video',
]
SITE_ID = 1
from easy_thumbnails.conf import Settings as thumbnail_settings
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
    ) + thumbnail_settings.THUMBNAIL_PROCESSORS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

ROOT_URLCONF = 'newsibleasia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "templates/v1"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'setting.context.setting_context',
                'setting.context.cms_context',
            ],
        },
    },
]

# PREPEND_WWW = True


#REPEND_WWW = False

WSGI_APPLICATION = 'newsibleasia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'newsibleasia.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'
STATIC_ROOT= BASE_DIR / 'staticfiles'


# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    os.path.join(BASE_DIR, 'static')
    #"/var/www/static/",
]
STATICFILES_STORAGE ="whitenoise.storage.CompressedManifestStaticFilesStorage"
# Add the custom admin CSS
ADMIN_CSS = 'css/custom_admin.css'
# for media file upload
MEDIA_ROOT =BASE_DIR /"upload"

MEDIA_URL="/upload/"
# for Esy thumnails
THUMBNAIL_ALIASES = {
        '': {
            'avatar': {'size': (50, 50), 'crop': True},
        },
    }
CKEDITOR_BASEPATH='/static/ckeditor/ckeditor/'
CKEDITOR_UPLOAD_PATH='upload/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar':'full',
        'removePlugins':'exportpdf',
        'extraPlugins': ','.join(
            [
                'codesnippet','widget','html5video','youtube',
            ]),
    },
}

EMAIL_HOST = 'mail.newsibleasia.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'no-reply@newsibleasia.com'
EMAIL_HOST_PASSWORD = '!@#$%^@1212'
EMAIL_USE_TLS = True
#EMAIL_USE_SSL = ''

#for recon
HUB_API_KEY = os.getenv('HUB_API_KEY', '')
HUB_SECRET_KEY = os.getenv("HUB_SECRET_KEY", "")
RECON_BASE_URL = os.getenv('RECON_BASE_URL', '')
PORTAL_NAME = os.getenv("PORTAL_NAME", "")